### ISSUE TITLE
How do you do a release build?

### ISSUE THREAD

**Issue by johnfn** [clemos/haxe-sublime-bundle#105]
This may be a dumb question, but I can't find any way to do a release build from Sublime Text. If there is such a way, could you document it? And if not, would it be possible to add one? :-) 

It seems to me like -debug is always being passed in as a flag when I'm doing an openfl project.

Thanks for the great work!

**Comment by jefvel** [comment]
Would be nice to have a release build menu option for HTML5 too. That doesn't seem to exist at the moment.
