### ISSUE TITLE
Commented out lines in the xml project file are treated as not being commented out.

### ISSUE THREAD

**Issue by johnfn** [clemos/haxe-sublime-bundle#107]
If I leave stuff like this in my project xml file:

    	
       	
        

Sublime Haxe will include these libraries for autocompletion (and will complain if I haven't installed them). Now, that may not seem so bad, but it seems like under some circumstances, including the same library twice may break autocompletion. For example, an xml file that includes the following:
	
	<haxelib name="openfl" />
	<haxelib name="flixel"/>
	<haxelib name="flixel-addons"/>
	
	
	

breaks autocompletion on flixel-addons. Drove me crazy until I figured out why!

**Comment by r3a1ay** [comment]
Should be fixed.
Because autocompletion uses openfl's display command to parse project.xml.
