### ISSUE TITLE
'(' and ',' do nothing

### ISSUE THREAD

**Issue by wilbefast** [clemos/haxe-sublime-bundle#125]
According to the readme: 

_Open parenthesis and comma keys display Haxe type hints in the status bar and inserts smart snippets_

I get nothing in the status bar and can't print either parentheses or commas. 

Arch Linux 64 bit.

**Comment by dy-dx** [comment]
I have this same issue when installing through Sublime Package Control. I had to clone master into my Packages folder in order to get '(' and ',' to work.
