### ISSUE TITLE
Allow setting default target

### ISSUE THREAD

**Issue by jorgenpt** [clemos/haxe-sublime-bundle#128]
When I select a build target, it should persist between launches of Sublime, or at least allow me to set it in a configuration file. Currently it defaults to Flash, and I do all my development with Neko, so I have to change it every time I start Sublime.

**Comment by madneon** [comment]
Please add such feature :)

**Comment by r3a1ay** [comment]
I'll try to implement this.

**Comment by madneon** [comment]
Thanks, it's working great :+1:
