### ISSUE TITLE
Keybindings Override Defaults

### ISSUE THREAD

**Issue by simonbw** [clemos/haxe-sublime-bundle#150]
The ctrl+enter keybinding for building the current target overrides the default Add Line behavior. The behavior also seems to be the same as the default build behavior ctrl+b. The ideal solution to this would be to allow custom keybindings.

**Comment by AndrewBelt** [comment]
For completion, I solved this by pasting

```json
	{ "keys": ["ctrl+enter"], "command": "run_macro_file", "args": {"file": "res://Packages/Default/Add Line.sublime-macro"} },
	{ "keys": ["ctrl+shift+enter"], "command": "run_macro_file", "args": {"file": "res://Packages/Default/Add Line Before.sublime-macro"} },
```
into the User Keybinding file.
