### ISSUE TITLE
Flambe build system appears to be broken since Aug. 19 builds.

### ISSUE THREAD

**Issue by volkipp** [clemos/haxe-sublime-bundle#164]
It looks like Flambe projects aren't working anymore with changes as of Aug. 19th. I'm on OSX, and when I try to select a build target with Control-Shift-Return, I get two items that say
Invalid Build
flambe.yaml
Invalid Build
flambe.yaml

If I hit escape or select one, it gives me the standard build targets for Flambe again. As another odd bug, I cannot edit my files in the project without a popup dialog saying that my file has changed on disk after about every keystroke. It looks like there are tmp files that are sticking around for every file that is edited.

**Comment by r3a1ay** [comment]
Fixed 'Invalid build' message.
It seems autocomplete and build are working fine.
If there is some other issue with flambe feel free to open a new issue.
