### ISSUE TITLE
expat.py woes on Ubuntu 11.04

### ISSUE THREAD

**Issue by jgranick** [clemos/haxe-sublime-bundle#17]
I wanted to try out the plugin, but unfortunately I keep getting stuck with the error that says it cannot load module pyexpat

I'm running Ubuntu 11.04. I have tried symlinking to /usr/lib/python2.6, and confirmed that /usr/lib/sublime-text-2/lib/python2.6 was in the paths that Sublime is searching, but it still doesn't work.

I appear to have Python 2.6.6 final installed.

Any ideas? Thanks!

**Comment by lyleaf** [comment]
I still didn't get it... Where can I find the /usr/lib/sublime-text-2/lib/ ?
