### ISSUE TITLE
OpenFL completion not working on some cases.

### ISSUE THREAD

**Issue by aaulia** [clemos/haxe-sublime-bundle#175]
Hi, this has been happening for a while now, but I'm too busy to report it, but it's getting annoying as of late. The symptoms that I gather is that whenever I access OpenFL's classes such as ```openfl.Assets``` or ```openfl.Lib``` the completion on the whole file suddenly broken because or error about missng lime classes.

![screenshot from 2014-11-01 11 53 26](https://cloud.githubusercontent.com/assets/161797/4870807/69944b54-6184-11e4-81d6-28d5c10e47e8.png)

The other error that I get is about nme not installed.

**Comment by alagatar** [comment]
Hi, any updates about fixing this?

**Comment by clemos** [comment]
I personnally don't use lime / OpenFL / NME much, so I don't have much time to handle this.
I agree it would be much better to use the appropriate framework commands to get the haxe compiler options needed for completion and stuff.
I also agree the bundle code is not very well structured / not easy to play with.
But I'm not sure it would be such a pain to implement.
I guess I could give it a try at some point, but I'd need someone to test it properly, as I usually only test on "basic" sample projects provided by the framework authors.
If someone is willing to spend some time trying it properly, please let me know and we'll figure a roadmap.

**Comment by clemos** [comment]
In the meantime, if lime is able to output an .hxml file, you should be able to use it for completion instead of the xml.
I know it's not ideal, as you'll have to switch between builds quite often to autocomplete / build, but it may be a workable workaround for now.

**Comment by cactusanctuary** [comment]
I was having a similar issue (#187), but it was complaining about lime.Assets. clemos directed me to this issue, and indeed, adding the `<haxelib name="lime" />` dependency fixed the autocompletion for now. 

The real fix will be much appreciated when it comes out :)

**Comment by willsonstar** [comment]
note about the quick fix, inserting <haxelib name="lime" /> in the project.xml is breaking my build. the auto correct works but I have to remove it before I can successfully compile anything.

**Comment by r3a1ay** [comment]
added temporary fix

**Comment by r3a1ay** [comment]
Please test.
