### ISSUE TITLE
Noticeable delay when opening first .hx file

### ISSUE THREAD

**Issue by Draknek** [clemos/haxe-sublime-bundle#178]
The first time I open a .hx file, there's a several second delay before the file loads.

I assume this is due to starting the Haxe server? But it could be something else. I tried setting haxe_build_server_mode and haxe_completion_server_mode to false to see if that would help, but it still starts the Haxe server when they're both disabled.

After the first file, everything loads fine, so it's not a big deal. Just a minor annoyance I notice once a day.

**Comment by dionjwa** [comment]
Yes, it would be great if the documentation was clear where the "haxe_build_server_mode" settings should go (a subdictionary "settings" in the project settings?). And if these options are obsolete, since the build server is always started, even if those are specified as false.
