### ISSUE TITLE
Adding defines to build

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [clemos/haxe-sublime-bundle#185]
My haxe (lime/openfl) project has some conditional compiling depending on defines I provide by hand (-DFAST_TESTS).
Can I somehow tell the build system to run lime with these defines enabled?

**Comment by JeriXNet** [comment]
If you use hxml maybe you should add space like this: `-D FAST_TESTS`

**Comment by clemos** [comment]
I'm not quite enough into lime, but I bet you can define these flags somewhere in the lime build file (xml ?)

**Comment by JeriXNet** [comment]
sorry for confusing about this, now I remember that with lime/openfl someone should use xml or hxp project files and hxml is just regenerated every build

**Comment by RudolfVonKrugstein** [comment]
I believe I can define that in the project.xml file, but actually I want different builds. One with "-D FAST_TESTS" enabled and one with it disabled.
Is that possible or do I have to edit my project.xml every time?

**Comment by clemos** [comment]
You can use several project.xml

**Comment by RudolfVonKrugstein** [comment]
Well, that it is simple enough.
