### ISSUE TITLE
Haxe autocompletion not working for classes in the same project, in ST2

### ISSUE THREAD

**Issue by cactusanctuary** [clemos/haxe-sublime-bundle#187]
Autocompletion used to work for me for these typical cases: 
* `instance.` -> would show public variables and functions
* `Class.` -> would show public static variables and functions

But I noticed it stopped working in the past week or so. I had recently upgraded all Haxe libraries using `haxelib upgrade`, and some of them were indeed upgraded but I don't remember which ones exactly. 

I've tried uninstalling the Haxe bundle via Sublime Text package control, and reinstalling it, but it didn't help. Any ideas on how to get it to work again? Thank you!

**Comment by cactusanctuary** [comment]
To clarify a bit more, ST2 is indeed able to find the classes when I'm instantiating a new instance or calling the class directly, and it knows where they are located. Just the public variables and functions can't be found anymore.

**Comment by clemos** [comment]
Do you get any error message in the ST console ?
Most people now use ST3, including myself, so ST3 support is much better than ST2. You may want to upgrade too.

**Comment by cactusanctuary** [comment]
I've upgraded to ST3, but I still don't have the autocompletion. 

No error messages appear in the ST console. I would expect it to show something when I hit the . for fetching (or failing to fetch) things for autocompletion, but nothing appears at all.

**Comment by cactusanctuary** [comment]
I'm on Mac OS X 10.9.5, in case that helps.

**Comment by cactusanctuary** [comment]
Still no error messages in the ST console, but I noticed in the status bar it says "Class not found : lime.Assets" when I'm typing, including after pressing the .

**Comment by clemos** [comment]
Then it's very likely a duplicate of #175

**Comment by cactusanctuary** [comment]
Yes, adding the lime dependency allows autocompletion to work again! Thank you :) 

I'll close this one and add a comment to that other issue that it was affecting me too.
