### ISSUE TITLE
call tips with new ST api

### ISSUE THREAD

**Issue by nadako** [clemos/haxe-sublime-bundle#188]
since build 3070 there's a very nice api allowing us to implement calltips like in visual studio. and it even supports html tags!

https://www.sublimetext.com/forum/viewtopic.php?f=2&p=65880

i'll probably play with it a bit in my toy hxsublime package and see if it's easy to port into this one

**Comment by lucas-jones** [comment]
+1

**Comment by clemos** [comment]
Yeah looks nice.
Any screenshot ?

**Comment by nadako** [comment]
![](http://take.ms/nM5i0)

**Comment by clemos** [comment]
Nice.
Type hinting could be easily moved to these popups.
