### ISSUE TITLE
Not working and freezing on OSX

### ISSUE THREAD

**Issue by josimard** [clemos/haxe-sublime-bundle#199]
Since today, the package is not working on multiple of our OSX 10.9.5 computers.
I can't find why, but the package is literally freezing Sublime Text 2.0.2 and the .hx files are opening empty.

**Comment by clemos** [comment]
I recently merged a couple PRs:
https://github.com/clemos/haxe-sublime-bundle/pulls?q=is%3Apr+is%3Aclosed
Maybe that's related @r3a1ay @andyli ?

**Comment by r3a1ay** [comment]
I'm testing the package in 2.0.2 version. Please wait.

**Comment by r3a1ay** [comment]
Meanwhile try to add this to your user settings:
```json
"haxe_use_cache" : false
```

**Comment by r3a1ay** [comment]
It works on my linux comp.
Can you share your build file (.hxml)?

**Comment by josimard** [comment]
It's a Flambe 4.1.0 project, so I cannot see no hxml files...
The project templates comes with an hxproj file: http://pastie.org/10031386

"haxe_use_cache" did not seems to solve the issue...

**Comment by r3a1ay** [comment]
Please share your *flambe.yaml* file.
*hxproj file* is used by flashdevelop.

**Comment by josimard** [comment]
Thanks,
It did fix the issue!

I tried on OSX 10.10+ and I did not run into the problem.

FIY, on OSX 10.9 I had Python 2.7.5
