### ISSUE TITLE
New syntax highlighting issues

### ISSUE THREAD

**Issue by haxiomic** [clemos/haxe-sublime-bundle#202]
I think a recent update has introduced some syntax highlighting bugs (I've tried uninstalling and reinstalling).

I believe this started today or yesterday

[example gif](http://recordit.co/bMWwMTEF1B)

**Comment by r3a1ay** [comment]
Thanks. 
Fixed.

**Comment by haxiomic** [comment]
Great stuff, :+1:, thanks

**Comment by alagatar** [comment]
I download as zip change files in sublime text, but issue stil present
