### ISSUE TITLE
Code generate settings

### ISSUE THREAD

**Issue by alagatar** [clemos/haxe-sublime-bundle#206]
Hi, Thanks for codegenerate feature, its great feature. Can it extends with settings?
How i can make that functions generates after current function/region, variable generates in header after last variable?

public var1:Bool;
//===insert generated variable here

function test():Void
{
    test//ctrl+shift+1    function
    var testVar//ctrl+shift+1    variable
}

//===insert generated function here

function anotherFunction():Void
{
}

**Comment by r3a1ay** [comment]
Hi.
Try to add this line to your user settings:
```json
"haxe_fields_order" : "VvFf"
```
Which means this order:
* Sorted static variables
* Sorted variables
* Sorted static functions
* Sorted functions

Unfortunately, you can not disable the sorting and grouping of static fields.
