### ISSUE TITLE
Can't seem to compile Flambe with ST3 on OSX: [Errno 2] No such file or directory: 'flambe'

### ISSUE THREAD

**Issue by dougcharnley** [clemos/haxe-sublime-bundle#216]
Hi guys, I'm feeling like a bit of a newbie here, I'm sure this is something simple but when I try to use "ctrl" + "enter" to compile the project (which compiles fine with terminal) I get this error:

[Errno 2] No such file or directory: 'flambe'
[cmd: ['flambe', 'run', 'html', '--debug', '--haxe-server', '6001']]
[dir: /Users/dougcharnley/Desktop/flambe-walk]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
[Finished]

I guess it looks like it can't find 'flambe'. This is a clean install on OSX 10.10.2 with ST3 and this haxe-sublime bundle installed through the packages manager.

How would I go about pointing it in the right direction to find flambe (if that is what the problem actually is!) I know that you have a bunch of settings such as "haxe_path" etc which you can change in the ST settings, but I guess they don't have anything to do with flambe right?

I think this is in the right area (last item), but I don't really get what he means:
https://github.com/markknol/flambe-guide/wiki/Troubleshooting

Any help at all would be hugely appreciated.

**Comment by r3a1ay** [comment]
Did you selected a build target with **ctrl+shift+b**?

**Comment by dougcharnley** [comment]
Yes, when I press ctrl+shift+b I get all the expected options, but no matter which I choose I get a similar error. The above pasted code is what I get if I select the "HTML5 - test" target. If I choose "Flash - test" instead I get: 

[Errno 2] No such file or directory: 'flambe'
[cmd: ['flambe', 'run', 'flash', '--debug', '--haxe-server', '6001']]
[dir: /Users/dougcharnley/Desktop/flambe-walk]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
[Finished]

**Comment by clemos** [comment]
It seems `flambe` is not installed correctly, or at least not in your `PATH`.
We should indeed add some setting like `flambe_path`.
Are you able to compile your project from a Terminal window ?

**Comment by dougcharnley** [comment]
Ah - yes I can compile perfectly fine using a terminal window.

**Comment by clemos** [comment]
It's more or less a ST issue, see:
http://stackoverflow.com/questions/25994666/setting-environment-variables-for-sublime-text-on-osx-desktop

**Comment by dougcharnley** [comment]
OK so are you saying I should be able to solve this without you needing to implement a new flambe_path variable? I'm new to Sublime text and so am not really sure what they're saying with these workarounds and how that would apply to Flambe. Thanks for your speedy response on this by the way!

**Comment by clemos** [comment]
We can certainly add this settings,
but meanwhile, you might be able to run ST with your current system environment variables, which would likely solve the problem, by typing `subl` from a Terminal rather than running ST from a desktop launcher; at least that's what SO seems to say.

**Comment by dougcharnley** [comment]
Hmm, I've just tried that, unfortunately with no change. I shut down Sublime, then used:

open /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl

in the terminal. Sublime opened and I dragged and dropped my Haxe project onto it. Then used ctrl+shift+b to select HTML5 test and then hit ctrl+enter to run and ended up with the exact same result.

As a side not, if highlight a Flambe class in my code, hold ctrl and then click it, I get the contextual menu. If I choose goto definition (Haxe) I get not found every time. Could this be part of the same problem?

**Comment by clemos** [comment]
I believe `open` is not wanted, just run : 
`/Applications/Sublime\ Test.app/Contents/SharedSupport/bin/subl`

**Comment by dougcharnley** [comment]
Either way (with or without the 'open') it does open Sublime text. If I then drag the project into the sublime window and select HTML5 test then hit ctrl + enter I still produces the same error I've been having:

[Errno 2] No such file or directory: 'flambe'
[cmd: ['flambe', 'run', 'html', '--debug', '--haxe-server', '6001']]
[dir: /Users/dougcharnley/Desktop/flambe-walk]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
[Finished]

It's as if Sublime just doesn't know what or where Flambe is...

**Comment by clemos** [comment]
What if you type just `flambe` in your Terminal ?
The bundle just assumes you have the flambe binary available in your PATH.

**Comment by dougcharnley** [comment]
This is what I get in terminal if I just type 'flambe' 

usage: flambe [-h] [-v] [--config CONFIG] <command> ...

Rapidly cook up games for HTML5 and Flash.

Optional arguments:
  -h, --help       Show this help message and exit.
  -v, --version    Print version and exit.
  --config CONFIG  Alternate path to flambe.yaml.

Commands:
    new            Create a new project scaffold.
    run            Build and run on a given platform.
    build          Build for multiple platforms.
    serve          Start a development server.
    clean          Delete build and cache files.
    haxe-flags     Show Haxe compiler completion flags.
    update         Update to the latest Flambe version.
    help           Get more help for any of these commands.
Dougs-iMac:~ dougcharnley$

**Comment by r3a1ay** [comment]
Run this commands in console (`View - Show Console`)
```python
import os, shutil
os.environ['PATH']
shutil.which('flambe')
```
What do you get?

**Comment by dougcharnley** [comment]
copy-pasting each of these lines into the console and hitting enter after each one I get this:

>>> import os, shutil
>>> os.environ['PATH']
'/usr/bin:/bin:/usr/sbin:/sbin'
>>> shutil.which('flambe')

**Comment by r3a1ay** [comment]
run this command in terminal:
```
whereis flambe
```

**Comment by dougcharnley** [comment]
nothing happens:

Dougs-iMac:~ dougcharnley$ whereis flambe
Dougs-iMac:~ dougcharnley$

**Comment by r3a1ay** [comment]
Try this one:
```
which flambe
```

**Comment by dougcharnley** [comment]
Aha: 

Dougs-iMac:~ dougcharnley$ which flambe
/usr/local/bin/flambe

**Comment by r3a1ay** [comment]
Try to open sublime with this command in terminal:
```
export PATH=$PATH':/usr/local/bin'; 'path to sublime_text'
```
Replace **'path to sublime_text'** with your path.

**Comment by dougcharnley** [comment]
It didn't seem to work I'm afraid:

Dougs-iMac:~ dougcharnley$ export PATH=$PATH':/usr/local/bin'; 'path to sublime_text'
-bash: path to sublime_text: command not found

**Comment by r3a1ay** [comment]
Try this command:
```
export PATH=$PATH':/usr/local/bin'; '/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
```

**Comment by dougcharnley** [comment]
Ah apologies I didn't notice the 'path to sublime_text'!

I get a no such file or directory error: 

Dougs-iMac:~ dougcharnley$ export PATH=$PATH':/usr/local/bin'; '/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
-bash: /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl: No such file or directory
Dougs-iMac:~ dougcharnley$

**Comment by r3a1ay** [comment]
Oh, sorry. Try this:
```
export PATH=$PATH':/usr/local/bin'; open '/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
```

**Comment by dougcharnley** [comment]
Slightly different result:

Dougs-iMac:~ dougcharnley$ export PATH=$PATH':/usr/local/bin'; open '/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
The file /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl does not exist.

**Comment by r3a1ay** [comment]
But you can open sublime with this command, right?
```
open /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl
```
Try previous command without quotes:
```
export PATH=$PATH':/usr/local/bin'; open /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl
```

**Comment by dougcharnley** [comment]
Yeah that worked!!

Dougs-iMac:~ dougcharnley$ /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl ; exit;
logout

[Process completed]

Now I can configure Sublime with ctrl+alt+b and then use ctrl+enter and it correctly builds and runs the project in the browser - thanks very much for you're help with this! So how did this solve it?

**Comment by r3a1ay** [comment]
As clemos said, the bundle assumes you have the `flambe` binary available in your `PATH`.
That command adds `flambe` path before open sublime.

**Comment by dougcharnley** [comment]
Ah I see, so as I've just found out - the above solution only works for that Sublime session. If you close Sublime and then open it again via the OSX dock for example - it no longer works. Opening Sublime in this manner (with the above line in terminal) temporarily fixes the path so that Sublime has access to flambe. Is that right? If so is it the case that the only way to fix this permanently (no matter how Sublime is opened) would be by adding a setting for the path to the Haxe plugin for Sublime?

**Comment by r3a1ay** [comment]
To fix the issue permanently you can try [this](http://www.cyberciti.biz/faq/appleosx-bash-unix-change-set-path-environment-variable/).

**Comment by dougcharnley** [comment]
Hmm, I've followed the instructions (I think) so that if I type 'echo $PATH' in terminal I now get:

Dougs-iMac:~ dougcharnley$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/bin

Which I think means I've successfully added '/usr/local/bin' to my PATH.

Unfortunately if I simply start Sublime the normal way and try and ctrl+enter to compile I still get the same old error:

[Errno 2] No such file or directory: 'flambe'
[cmd: ['flambe', 'run', 'html', '--debug', '--haxe-server', '6001']]
[dir: /Users/dougcharnley/Desktop/flambe-walk]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
[Finished]

Did I do something wrong?

**Comment by r3a1ay** [comment]
Did you find a way to fix the issue permanently?
You can create custom sublime text launcher with this command:
```
export PATH=$PATH':/usr/local/bin'; open /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl
```
I can't help you with this. Try [this](http://apple.stackexchange.com/questions/115114/how-to-put-a-custom-launcher-in-the-dock-mavericks) or google another solution.
I'll close this issue because it's not relevant to the bundle.

**Comment by dougcharnley** [comment]
Great - thankyou! I appreciate the problem was more of a Sublime/OSX issue and not a problem with your bundle - so thanks for all the help that you gave me anyway!
