### ISSUE TITLE
HaxePunk autocompletion

### ISSUE THREAD

**Issue by stasuss** [clemos/haxe-sublime-bundle#217]
when trying to use autocompletion in simple HaxePunk project, there is no completion. There is only error shown on statusbar, saying that BitmapData class was not found. But compilation is ok though.

HaxePunk engine uses flash.display.BitmapData, so i think haxe completion server somehow misses it.
Is it possible to switch plugin to compiler completion and not server one? It seems to me that it may be helpful, because in FlashDevelop completion works and it uses compiler completion.
UPD: tested in FD with server completion - everything is fine.

**Comment by stasuss** [comment]
so. magically issue solved by me. today i tried heaps lib and it reqired 3.2 haxe version, so i've replaced my installed one with this. now i've tried using autocompletion with haxepunk on this version and got some other error. something about vectors or whatever. but compilation was success. then i decided to revert to 3.1.3. and.. everything is ok. i really don't know what was it. may be my haxe version was too old or whatever.

and thank you for great lib)

**Comment by stasuss** [comment]
The next day it returned. Have not changed much. Just was testing my project and noticed that autocompletion fails again.

**Comment by r3a1ay** [comment]
Can you share your build file (`project.xml`)?

**Comment by stasuss** [comment]
yes. shure. but it is nearly default.
<code><?xml version="1.0" encoding="utf-8"?>
<project>
	<meta title="metroidvania" package="com.curlybrace.app" version="1.0.0" company="" />

 	<app file="Main" main="Main" />

	<window fps="60" background="0x333333" />
	<window width="640" height="480" resizable="false" unless="mobile" />
	<window fullscreen="true" if="mobile" />
	<window orientation="landscape" vsync="true" antialiasing="0" if="cpp" />

	<source path="src" />
	
	<haxelib name="format" />
	<set name="legacy" />
	<haxelib name="openfl" />
	<haxelib name="openfl-bitfive" if="html5" />
	<haxelib name="HaxePunk" />
	
	<assets path="assets/graphics" rename="graphics" include="*.png|*.jpg" />
	<assets path="assets/audio" rename="audio" include="*.mp3" if="flash" />
	<assets path="assets/audio" rename="audio" include="*.wav|*.ogg" unless="flash" />
	<assets path="assets/font" rename="font" include="*.ttf" />
	<assets path="assets/levels" rename="levels" include="*.xml" />
	<assets path="assets/shaders" rename="shaders" include="*.vert|*.frag" />
	
	<icon path="assets/HaxePunk.svg" />
</project><code>

**Comment by r3a1ay** [comment]
Please test.

**Comment by stasuss** [comment]
wow. thank you! it's alive! +1
