### ISSUE TITLE
Could not process argument with lowercase project.xml app path 

### ISSUE THREAD

**Issue by scriptorum** [clemos/haxe-sublime-bundle#218]
Running Sublime 3 on a Mac with updated haxelibs.  I'm having trouble with code completion, in that the status bar shows the error "Could not process argument xxx" where xxx is the value of the path attribute for the app tag in the project.xml file. This problem only occurs when the path attribute begins with a lower case letter. For example, this triggers the error:

```
	<app main="Main" path="export" file="MyApp" />
```
But this is fine:
```
	<app main="Main" path="Export" file="MyApp" />
```

I don't have any problems using the build system, however.

**Comment by stasuss** [comment]
remembered having same issue. solved it by removing path attribute completely

**Comment by r3a1ay** [comment]
Should be fixed in previous commits.
