### ISSUE TITLE
weird syntax highlighting

### ISSUE THREAD

**Issue by nadako** [clemos/haxe-sublime-bundle#219]
![](http://take.ms/CJgto)

**Comment by nadako** [comment]
one more, why default is different than null in this context:
![](http://take.ms/nApo2)

**Comment by nadako** [comment]
one more: why `set` is highlighted here?
![](http://take.ms/5qE1v)

**Comment by br4nnigan** [comment]
i have another one, notice the type of the second
![bildschirmfoto 2015-04-13 um 17 10 11](https://cloud.githubusercontent.com/assets/10244835/7118504/fbbfa87e-e1ff-11e4-8178-a6ea901d7879.png)

**Comment by nadako** [comment]
another one:
![](https://dl.dropboxusercontent.com/u/487675/constraints.gif)

**Comment by nadako** [comment]
and another one:
![](http://take.ms/d2e1Y)

**Comment by r3a1ay** [comment]
Thanks, I'll try to fix that.
Is this feature documented somewhere?
`class` A<**T:{}**> {}

**Comment by nadako** [comment]
Sure, it's type constraints: http://haxe.org/manual/type-system-type-parameter-constraints.html

**Comment by r3a1ay** [comment]
**{}** in this case is `typedef`, right?

**Comment by nadako** [comment]
It's a structure, how is that related to `typedef`? `T:{}` simply means that it should be an object (because any object will unify with an empty structure).

**Comment by r3a1ay** [comment]
Ok.

**Comment by r3a1ay** [comment]
Fixed.

**Comment by nadako** [comment]
Shouldn't `default` be highlighted here?
![](http://take.ms/smqIa)

**Comment by r3a1ay** [comment]
Fixed.

**Comment by br4nnigan** [comment]
Got another (javascript)!
<img width="185" alt="firefox - - 3 juli 2015 11 35 screen shot" src="https://cloud.githubusercontent.com/assets/10244835/8496728/c033cb0c-2177-11e5-89e8-5f473c666309.png">

**Comment by r3a1ay** [comment]
Javascript? How can you use js code in haxe without **untyped** keyword? I'm missing something?

**Comment by br4nnigan** [comment]
Oops i mixed something up here.
