### ISSUE TITLE
Build problems again on build 3080 and 3083

### ISSUE THREAD

**Issue by ciscoheat** [clemos/haxe-sublime-bundle#221]
I'm experiencing same problem as #209 again, also on build 3083 (Win 7 x64). This time the syntax highlighting disappeared, and after using "Set Syntax: Haxe" on one file and pressing Ctrl-Enter, no output is generated. It finds all the hxml files however with Ctrl-B, giving me a selection, but same result for all with Ctrl-Enter.

Tried it on multiple projects and on Flashdevelop, so there's nothing wrong with the installation or compilation server. One or more haxe.exe processes are still hanging after I close Sublime.

I have cloned this repo and installed it manually, so let me know if I can assist in debugging.

**Comment by r3a1ay** [comment]
Try to reinstall sublime text and use default settings.

**Comment by ciscoheat** [comment]
That took care of the missing syntax highlighting, but still having the same problem with compiling using Ctrl-Enter.

**Comment by r3a1ay** [comment]
> It finds all the hxml files...  

Can you share them?

**Comment by ciscoheat** [comment]
Sure, it's this repo: https://github.com/ciscoheat/mithril-hx
It should compile right out-of-the-box with `haxe webshop.hxml` for example. There's even a sublime project file included there.

**Comment by r3a1ay** [comment]
Works in my case.
What you get in sublime's console (View-Show console) after you press Ctrl+Enter?

**Comment by ciscoheat** [comment]
```
Starting Haxe server on port 6001
Package Control: No updated packages
Running haxe --connect 6001 --cwd E:\Projects\Haxe\mithril --no-output -cp example -lib mithril -js bin/webshop/webshop.js -main webshop.Webshop
```

**Comment by r3a1ay** [comment]
Try to comment these lines in HaxeComplete.py (line ~2230):
```python
if os.name == "nt":
    err_type = WindowsError
```

**Comment by ciscoheat** [comment]
Sorry, that didn't change anything. :(

**Comment by r3a1ay** [comment]
Ok, maybe this will help:
```python
err_type = Exception
```

**Comment by ciscoheat** [comment]
That didn't help either. I'm studying the source (HaxeComplete.py), where is the building taking place? Also, what is the purpose of `--no-output` when compiling?

**Comment by r3a1ay** [comment]
In your case here:
```python
class HaxeExecCommand(ExecCommand):
def run(...)
```
But I'm not sure.

**Comment by r3a1ay** [comment]
Try to replace all `append_data` methods with `append_string`.

**Comment by ciscoheat** [comment]
Sorry, no luck there. It generates output if I comment out `args.append( ("--no-output",) )` around line 1547.

**Comment by r3a1ay** [comment]
It seems that [this](https://github.com/andyli/haxe-sublime2-bundle/commit/79c97d7c311f446fc75d01d04a4e2fd1fcd8fc30) commit causes this issue.  
Try to indent this code:
```python
        if build.yaml is not None :
            # Call out to `flambe haxe-flags` for Flambe completion
            res, err = runcmd( ["flambe","--config" , build.yaml, "haxe-flags"] )
            if err :
                print("Flambe completion error: " + err)
            else:
                args += [(arg,) for arg in res.split("\n")]
            args.extend( build.args )
        elif build.nmml is not None :
            settings = view.settings()
            haxelib_path = settings.get("haxelib_path" , "haxelib")
            # print(build.nmml, HaxeBuild.nme_target[1].split(" ")[0])
            res, err = runcmd( [
                haxelib_path, 'run', 'openfl', 'display',
                build.nmml, HaxeBuild.nme_target[1].split(" ")[0]] )
            if err :
                print("OpenFl completion error: " + err)
            else:
                args += [(arg,) for arg in res.split("\n")]
        else:
            args.append( ("--no-output",) )
            output = build.output
            if output is None :
                output = "no-output"
            #args.append( ("-cp" , plugin_path ) )
            #args.append( ("--macro" , "SourceTools.complete()") )

            args.extend( build.args )
```

**Comment by ciscoheat** [comment]
Indenting cleared the whole command line buildup, so that didn't work. But I found no further usage of the `output` var, so changing the last else to:

```python
        else:
            if build.output is None :
                args.append( ("--no-output",) )
            #args.append( ("-cp" , plugin_path ) )
            #args.append( ("--macro" , "SourceTools.complete()") )

            args.extend( build.args )
```

Seems to have fixed the problem. Let me know if I should make a PR.

**Comment by r3a1ay** [comment]
It was my mistake in [this](https://github.com/clemos/haxe-sublime-bundle/commit/ce11a8dc59ebb8b73d21248fd03b588f402f4b4f) commit.
Please try the lattest version. I'm sure it fixes the issue.
Thanks for testing.

**Comment by ciscoheat** [comment]
It works, thanks. :)

**Comment by andyli** [comment]
It works on my side too. Sorry for the earlier breaking commit.
I've added a test in #222, so hopefully it will never be broken again :)
