### ISSUE TITLE
option to disable error highlight

### ISSUE THREAD

**Issue by stasuss** [clemos/haxe-sublime-bundle#223]
sometimes it catches strange errors when i type. it can highlight full method with error "class X not found" even if X is single letter of what i was going to type.

it is also annoying that i can't get rid of those red lines. they persist even after successful compilation.

for me it is enough to see line number and description of the error in results. so is it possible to disable this highlighting?

**Comment by r3a1ay** [comment]
Check latest version.
Code completion errors should disappear after 5 sec.

**Comment by r3a1ay** [comment]
Can I close this issue?
Or you still want an option to disable the error highlighting at all?

**Comment by stasuss** [comment]
It would be nice to have on though

**Comment by r3a1ay** [comment]
Ok

**Comment by stasuss** [comment]
Thank you!)

**Comment by r3a1ay** [comment]
To disable error highlighting add this line to your settings:
```json
"haxe_errors_style": "none",
```
