### ISSUE TITLE
Typing Lag

### ISSUE THREAD

**Issue by lucidfext** [clemos/haxe-sublime-bundle#224]
Hi, I'm using ST3 3083 on Windows 8.1.
There is a noticeable lag(about 2~3 seconds) when type character which involved with code hint. I thought this was related with haxe completion server but in flashdevelop It works smoothly.

I am bit confused because It seems there is no one who got problem like me.

**Installed Packages**
-Haxe
-Numix Theme

**Comment by stasuss** [comment]
i also have such thing. it seems to me that project is recompiled at this time, because my hdd works. but after that this lag seems to go away.

**Comment by lucidfext** [comment]
I didn't know much about completion mechanism of flashdevelop, thanks.
BTW, I got a little bit different problem with you. Lag occurs all the time when I code so It drives me mad :(

**Comment by r3a1ay** [comment]
Yes, I'm planning to optimize the completion.
Meanwhile you can disable auto completion:
```json
"auto_complete": false
```
To show the completion manually press **ctrl+spase** or **alt+/**.

**Comment by lucidfext** [comment]
Thanks!

**Comment by stasuss** [comment]
by the way. i got now the cause of the issue, that i'm suffering (at least i think i got). i'm storing sources on dropbox and sublime constantly asks me if i want to reload file, that i'm editing.
now i understood that this happens right after autocomplete is shown.
as i understand, project is recompiled and somehow file appears to be changed. don't know now if it will also change without the dropbox, but it surely changes after autocompletion.

what may cause this?

**Comment by shinmai** [comment]
> Meanwhile you can disable auto completion:
How can manual completions be used to complete method parameters? That's the most useful function for me, and I can't seem to get that working without enabling autocompletion.

**Comment by r3a1ay** [comment]
I hope this will help.

**Comment by r3a1ay** [comment]
Now the lag appears during the file switching.
I'll try to fix that.
