### ISSUE TITLE
No .HXP Project Support?

### ISSUE THREAD

**Issue by genesisbryant** [clemos/haxe-sublime-bundle#229]
The plugin doesn't currently support .hxp projects for Lime/OpenFL programs, right? Here's the .hxp spec; it's meant to be a substitute for the project.xml file.

http://www.openfl.org/documentation/projects/project-files/hxp-format/

Is there any way to enable the plugin to use .hxp project definitions instead of project.xml ones?

Cheers! :)

**Comment by r3a1ay** [comment]
Please test.
Try to use `import **lime.**project.*;` in `*.hxp` files if you will have issues with autocomplete or compilation.

**Comment by genesisbryant** [comment]
It works!! :) :) Thank you so much!! :D
