### ISSUE TITLE
[QUESTION/REQUEST] some missing completes

### ISSUE THREAD

**Issue by lewislepton** [clemos/haxe-sublime-bundle#232]
first to say, thanks for this bundle, really well done, thanks for the help as well and just in general.
there have been a few things i have noticed that seem to be missing within it though.

say things like ```drawRect()``` do not pop up on auto-complete. there are possible, since im just now working thorugh learning HAXE, and also things like ```beginFill()``` ```endFill()``` etc

whilst i know that you cant get everything right away, was just noting them down to help.
if i can come across anymore, ill let you know ;)

again, thanks for the great work ;)

**Comment by lewislepton** [comment]
also just to add.
on making a new class, nothing pops up at all once typing on a blank class. i dont know if this is because you need certain things to be imported first to start, so please excuse if that is the case.

but just wanted to say

thanks ;)

**Comment by rpidstryhach** [comment]
Try updating Haxe to 3.2.0.
Also, when you are creating a new class through sidebar context menu, popup arrives at the bottom of the screen asking to enter class name, you might've missed that.
