### ISSUE TITLE
[POSSIBLE ERROR] no node js target when running 

### ISSUE THREAD

**Issue by lewislepton** [clemos/haxe-sublime-bundle#233]
hello,

now i have installed node thorugh haxelib. just so i can try the html5 stuff, dont want flash in my alley ;)

but on trying have seemed to have ran into a possible bug. possible i say. because it may be my setup, which i will show. but it says it can find a folder which does not exist once node has been installed. got some screenshot just to show, but hopefully will help

thanks

![screen shot 2015-05-14 at 00 23 45](https://cloud.githubusercontent.com/assets/11299322/7623227/e3737150-f9cf-11e4-98e1-542dd67617ac.png)

![screen shot 2015-05-14 at 00 25 36](https://cloud.githubusercontent.com/assets/11299322/7623229/e79910f0-f9cf-11e4-8a72-d012d27c0ad0.png)

**Comment by clemos** [comment]
This seems to be an issue with lime itself
