### ISSUE TITLE
Bug when typing period after any number

### ISSUE THREAD

**Issue by rpidstryhach** [clemos/haxe-sublime-bundle#235]
Noticed this recently, just figured out what causes it.
Looks like it tries to trigger a hint, which appears for a moment and then this pops out:

![wbpwobqcac-dwojrrnfhfbby4f7asafpnvjmlgekmtc](https://cloud.githubusercontent.com/assets/8464160/7844934/47d721e0-04bc-11e5-84fb-ab9722203cc0.png)

**Comment by r3a1ay** [comment]
Do you have any error message in console?

**Comment by rpidstryhach** [comment]
Yeah, here it is.
![z9x_dhzeuprtwd62kma6pyzo5rqryzr7yfjkwmhkfiq](https://cloud.githubusercontent.com/assets/8464160/7847232/f188b8ee-04ca-11e5-8b82-847dfe56a948.png)
This is a position where I'm typing at the moment.

**Comment by r3a1ay** [comment]
I hope this helps.

**Comment by rpidstryhach** [comment]
Yeah, seems fixed, thanks!
