### ISSUE TITLE
 [QUESTION] Passing arguments to a build compilation

### ISSUE THREAD

**Issue by xbelanch** [clemos/haxe-sublime-bundle#236]
I don't know if it's possible to passing arguments to a specific build i.e. ``lime test cpp -debug`` maybe I missed something related to a specific build config file or perhaps depends on build hxml files. I'd appreciate some help.

**Comment by r3a1ay** [comment]
Select **C++ test** or **C++ build only** to compile the project in debug mode.
To pass other arguments add them in [build config file](http://www.openfl.org/documentation/command-line-tools/project-files/xml-format/) (using`<haxedef/>`).

**Comment by xbelanch** [comment]
It works! Thanks!
