### ISSUE TITLE
Autocomplete micro lag

### ISSUE THREAD

**Issue by anonrab** [clemos/haxe-sublime-bundle#243]
Each time requested autocomplete for haxe in sublime text 3 (Classes autocomplete, function parameters autocomplete) micro lag happens (50-100 millisecond). It's very annoying, when you input some code fast, and get lag each character inputed.

I have very powerful pc with lot of ram and ssd, so it can't be fault of my pc. And in the flash develop autocomplete happens instantly, with no delay. 

I can record video of this, if this issue only my problem. But i try to use sublime with haxe-sublime-bundle on windows pc and mac notebook, no difference - same lag on each device.

**Comment by r3a1ay** [comment]
This package uses [compiler based](http://haxe.org/manual/cr-completion-overview.html) autocomplete. This means that the file must be saved and *compiled*. Which causes the *lag*. 

You can disable autocomplete with this setting:
```json
"haxe_auto_complete": false
```
Use these shortcuts to display completion list and hints manually:
* **Ctrl+Space** - display haxe completion
* **Ctrl+Alt+Space** - display type completion
* **Ctrl+Shift+Space** - show code hint

**Comment by anonrab** [comment]
Thanks, i will use manual autocomplete. But i have few questions.
It's hard to me, to find haxe-sublime-bundle settings, it's hidden deep in the plugin. Maybe do shortcut to it in Preferences -> Package Settings, like it's done in many other sublime plugins?

I know nothing about sublime plugin development, but can plugin save file to memory or temp folder and compile it asynchronously? 

FlashDevelop autocomplete is compiler based too, but why their autocomplete works instantly? (i am not sure about this, at least they use haxe autocomplete server)

**Comment by r3a1ay** [comment]
> Maybe do shortcut to it in Preferences -> Package Settings, like it's done in many other sublime plugins   

Added.

> ... and compile it asynchronously?

I think it's possible, but I don't plan to implement it, because I use manual autocomplete.
If you know python, you can try to implement this feature.

Flash Develop uses mixed autocomplete (internal/haxe compiler) as far as I know.
