### ISSUE TITLE
Sublime Text 3 hangs with any hx file

### ISSUE THREAD

**Issue by RealJTG** [clemos/haxe-sublime-bundle#247]
Sublime Text 3 hangs when I trying to open any .hx file or executing "Haxe: Choose Build Targed". plugin_host.exe runs `haxe --wait 6001` eating CPU and causes editor to become unresponsive. No any info in console.

![image](http://i.imgur.com/7EN2FbH.png)

I've tried ST3 clean installation and portable version, install bundle through Package Control and directly to /Packages from git — the problem still exists.

Sublime Text 3 build 3083 x86 on Windows 7
Haxe 3.1.3

UPD: ST2 also affected

**Comment by r3a1ay** [comment]
Please try to edit line 991 in HaxeComplete.py:
```python
while prev != f and ( project_folder is None or project_folder in f ):
```
To:
```python
while False:
```

**Comment by RealJTG** [comment]
Yes, this helps

**Comment by r3a1ay** [comment]
Thanks, I'll try to fix that line.

**Comment by r3a1ay** [comment]
Please test.

**Comment by RealJTG** [comment]
I'm able to reproduce this on another Windows machine and it's kinda weird :D 

Drop [large xml](https://gist.githubusercontent.com/RealJTG/5afe035f0de41b66da3c/raw/6b2e87bfe5c61b96e3b44feb1686f1ada2bf8da7/gistfile1.txt) somewhere in file path (or just disk root) and you should see something like this:
```
self.find_hxml("D:\test\Breakout\source")
self.find_nmml("D:\test\Breakout\source")
self.find_yaml("D:\test\Breakout\source")
self.find_hxml("D:\test\Breakout")
self.find_nmml("D:\test\Breakout")

<Found D:\test\Breakout\Project.xml>

self.find_yaml("D:\test\Breakout")
self.find_hxml("D:\test")
self.find_nmml("D:\test")
self.find_yaml("D:\test")
self.find_hxml("D:\")
self.find_nmml("D:\")

<Found D:\large.xml - got stuck parsing it>
```

**Comment by r3a1ay** [comment]
Interesting, :D. 
@clemos, should we check the size of *.xml files?

**Comment by clemos** [comment]
Yeah I guess it would be a good idea :/ 100k is probably already huge for a build file....

**Comment by r3a1ay** [comment]
Long lines in ``xml`` files cause this issue.
Added a limit in 200 characters per line.
