### ISSUE TITLE
Build selection / discovery failing even when specifying haxe_builds setting in project

### ISSUE THREAD

**Issue by wighawag** [clemos/haxe-sublime-bundle#252]
Sublime always fail as it try to execute "haxe build.hxml" while my hxml is named differently 

My hxml file is specified using 

```json
{
	"folders":
	[
		{
			"path": "."
		}
	],
	"settings":
	{
		"haxe_builds":
		[
			"build@project-windows.hxml"
		]
	}
}
```

I tried different value including full path (I use sublime text 3) but it always fail

as a workarround I created a "build.hxml" file containing 
```
-cmd cd build
-cmd haxe project-windows.hxml
```

and it works

**Comment by wighawag** [comment]
actually it works but not when using ctrl+b which I was using.
It works using ctrl+enter

**Comment by clemos** [comment]
Ctrl+B is managed by Sublime Text, the correct shortcut is Ctrl+Enter
