### ISSUE TITLE
Wiki Request: Ease step by step installation guide

### ISSUE THREAD

**Issue by mehdadoo** [clemos/haxe-sublime-bundle#253]
I would like to know how is it possible to use your package.
I have no idea how to download your package, where to copy it on my ubuntu machine. All i want is color coding for my haxe documents, i don't want to read many articles on what sublime is and how to type in it's console. Gedit gives me color coding, but there is no auto-ident.
Thank you for your efforts.

**Comment by clemos** [comment]
Installation is fairly straightforward using Package Control : 
https://github.com/clemos/haxe-sublime-bundle/wiki/Installation#sublime-package-control
(Install package control, restart Sublime, Ctrl+Shift+P, Install Package, Haxe)
