### ISSUE TITLE
Console attach to swf when compiling with hxml?

### ISSUE THREAD

**Issue by IkonOne** [clemos/haxe-sublime-bundle#255]
I have a project that I am building with a build.hxml.  When I was using Openfl, ST would output all trace and errors thrown into the ST console.  I can't figure out how to make that happen with my hxml file.

I am using the latest and greatest versions of everything on osx.

My build file:
```
-cp Genome2D/Genome2D-Core/src
-cp Genome2D/Genome2D-ContextFlash/src
-cp Genome2D/Genome2D-ContextCommon/src
-cp G2DTest/src

-lib actuate
-lib msignal
-swf-lib Genome2D/Genome2D-ContextFlash/lib/AGAL.swc

-D fdb
-debug

-D genome2d_stage3donly

-main Main

-swf-version 12.0
-swf out/flash/G2DTest.swf
-swf-header 480:320:60:555555

-cmd open out/flash/G2DTest.swf
```

Maybe I am just doing it wrong?

I am having another issue where I can run ```haxe build.hxml``` from the command line and the swf is generated perfectly.  However, when I build in ST, a macro in Genome2D fails to run and the resulting swf throws errors.  Should I create a different issue for this? (This is the macro that is not running: https://github.com/pshtif/Genome2D-Core/blob/master/src/com/genome2d/macros/MGPrototypeProcessor.hx)

**Comment by IkonOne** [comment]
It looks like the issue is tied to Genome2D somehow.

**Comment by IkonOne** [comment]
I'm closing this because I'm the only commenter and I'm not pursuing this solution anymore.

**Comment by clemos** [comment]
Yeah, sorry. 
I figured your issue was solved, after your previous message.
As for traces in console output, I don't really have clues, so...

**Comment by IkonOne** [comment]
Hey no problem.  I simply didn't want to leave it here when I don't even remember submitting it.
