### ISSUE TITLE
Broken in ST4

### ISSUE THREAD

**Issue by rwols** [clemos/haxe-sublime-bundle#278]
This package doesn't work anymore in ST4. The following diff makes it start:

```diff
diff --git a/.python-version b/.python-version
new file mode 100644
index 0000000..cc1923a
--- /dev/null
+++ b/.python-version
@@ -0,0 +1 @@
+3.8
diff --git a/HaxeComplete.py b/HaxeComplete.py
index b7fd051..5323682 100644
--- a/HaxeComplete.py
+++ b/HaxeComplete.py
@@ -73,7 +73,7 @@ except (AttributeError):
 # For parsing xml
 
 from xml.etree import ElementTree
-from xml.etree.ElementTree import XMLTreeBuilder
+from xml.etree.ElementTree import TreeBuilder as XMLTreeBuilder
 
 try :
     from elementtree import SimpleXMLTreeBuilder # part of your codebase
```

Consider patching it with this diff.

**Comment by Lbones-ai** [comment]
hey man, I've made the pull up request for HaxeComplete.py, but how do you change the python version?
I'm a bit out of my depth here

**Comment by clemos** [comment]
Hi :wave:
Can you please file a PR with the `.python-version` file ?
The rest has already been merged as per https://github.com/clemos/haxe-sublime-bundle/pull/277
Thanks :pray: :)

**Comment by rwols** [comment]
You can copy the above diff to a file and use something like `git apply path/to/patch.file`.

> Can you please file a PR with the .python-version file ?

That would require me to fork this entire repo, a simple patch would suffice no? Though I've see you've already committed 0dccea21ee890b0c266a231defc6f258453ed4d6. I don't know if that would work in the python 3.3 runtime.

But it's as simple as creating a .python-version file with content `3.8`.

https://www.sublimetext.com/docs/api_environments.html

**Comment by clemos** [comment]
Alright, I did it directly through github 
https://github.com/clemos/haxe-sublime-bundle/commit/4455bd1375d831532b6b43d6ef7d13bbeee26715
Let me know if it fixes your issues :ok_hand:

**Comment by rwols** [comment]
> Alright, I did it directly through github

Err... What if my patch doesn't work at all? Please verify locally.

**Comment by clemos** [comment]
:ok_hand:

**Comment by rwols** [comment]
Note that this package is still a branch-based entry in package_control_channel; so all ST3 users are getting this modification immediately. While the .python-version file for those users is harmless, make sure the modified import works for ST3 as well.
